### ISSUE TITLE
返回数据不是合法的JSON格式

### ISSUE THREAD

**Issue by RobaLinan** [mrchi/lark-dalle3-bot#3]
在飞书开放平台，事件订阅，请求地址中添加 http://IP:Port 之后无法保存，提示返回数据不是合法的JSON格式

**Comment by mrchi** [comment]
代码里配置的 URL path 是 `/dalle3`，所以在飞书或 lark 开放平台中填写的事件推送地址应该是

```
http(s)://ip:port/dalle3
``` 

抱歉文档中没有说明 晚上我更新一下

**Comment by mrchi** [comment]
Resolved in https://github.com/mrchi/lark-dalle3-bot/commit/5e95940ee6607a9c1a3e7db7d4d07ebbdf7b12d2
